// flow-typed signature: 8117bfb4c13e7fec7633a07ddba65f14
// flow-typed version: <<STUB>>/react-proptypes_v^1.0.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-proptypes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-proptypes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-proptypes/index' {
  declare module.exports: $Exports<'react-proptypes'>;
}
declare module 'react-proptypes/index.js' {
  declare module.exports: $Exports<'react-proptypes'>;
}
